//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEIC_SaoKhue.Models
{
    using System;
    
    public partial class BAOLUU
    {
        public System.DateTime NgayBaoLuu { get; set; }
        public int MaHV { get; set; }
        public string TenHV { get; set; }
        public string SDTHV { get; set; }
        public string MaLop { get; set; }
        public int MaHD { get; set; }
    }
}
