//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEIC_SaoKhue.Models
{
    using System;
    
    public partial class DANGKY
    {
        public string MaLop { get; set; }
        public string SDT { get; set; }
        public System.DateTime NgayDK { get; set; }
        public string TenDK { get; set; }
        public System.DateTime NgayKhaiGiang { get; set; }
        public int MaDK { get; set; }
    }
}
