//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TOEIC_SaoKhue.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Data.SqlClient;
    using System.Linq;
    using System.Web;

    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
            Database.Connection.StateChange += Connection_StateChange;
        }

        private void Connection_StateChange(object sender, System.Data.StateChangeEventArgs e)
        {
            if(HttpContext.Current.Session["taikhoan"] != null)
            {
                string username = ((TAIKHOAN)HttpContext.Current.Session["taikhoan"]).Username;
                if (Database.Connection.State == System.Data.ConnectionState.Open)
                {
                    SqlConnection.ClearPool((SqlConnection)Database.Connection);
                    using (SqlCommand cmd = new SqlCommand("EXECUTE AS USER = '" + username + "'", (SqlConnection)Database.Connection))
                    {
                        cmd.ExecuteNonQuery();
                    }
                }
            }            
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<TAIKHOAN> sp_DangNhap(string username, string password)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TAIKHOAN>("sp_DangNhap", usernameParameter, passwordParameter);
        }
    
        public virtual ObjectResult<CAHOC> sp_LietKeCaHoc()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CAHOC>("sp_LietKeCaHoc");
        }
    
        public virtual int sp_ThemCaHoc(string giohoc, string ngayhoc)
        {
            var giohocParameter = giohoc != null ?
                new ObjectParameter("giohoc", giohoc) :
                new ObjectParameter("giohoc", typeof(string));
    
            var ngayhocParameter = ngayhoc != null ?
                new ObjectParameter("ngayhoc", ngayhoc) :
                new ObjectParameter("ngayhoc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemCaHoc", giohocParameter, ngayhocParameter);
        }
    
        public virtual int sp_XoaCaHoc(Nullable<short> mach)
        {
            var machParameter = mach.HasValue ?
                new ObjectParameter("mach", mach) :
                new ObjectParameter("mach", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaCaHoc", machParameter);
        }
    
        public virtual int sp_CapNhatChuongTrinh(string mact, string tenct, string thoigian, Nullable<double> hocphi)
        {
            var mactParameter = mact != null ?
                new ObjectParameter("mact", mact) :
                new ObjectParameter("mact", typeof(string));
    
            var tenctParameter = tenct != null ?
                new ObjectParameter("tenct", tenct) :
                new ObjectParameter("tenct", typeof(string));
    
            var thoigianParameter = thoigian != null ?
                new ObjectParameter("thoigian", thoigian) :
                new ObjectParameter("thoigian", typeof(string));
    
            var hocphiParameter = hocphi.HasValue ?
                new ObjectParameter("hocphi", hocphi) :
                new ObjectParameter("hocphi", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatChuongTrinh", mactParameter, tenctParameter, thoigianParameter, hocphiParameter);
        }
    
        public virtual ObjectResult<CHUONGTRINH> sp_LietKeChuongTrinh()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<CHUONGTRINH>("sp_LietKeChuongTrinh");
        }
    
        public virtual int sp_ThemChuongTrinh(string mact, string tenct, string thoigian, Nullable<double> hocphi)
        {
            var mactParameter = mact != null ?
                new ObjectParameter("mact", mact) :
                new ObjectParameter("mact", typeof(string));
    
            var tenctParameter = tenct != null ?
                new ObjectParameter("tenct", tenct) :
                new ObjectParameter("tenct", typeof(string));
    
            var thoigianParameter = thoigian != null ?
                new ObjectParameter("thoigian", thoigian) :
                new ObjectParameter("thoigian", typeof(string));
    
            var hocphiParameter = hocphi.HasValue ?
                new ObjectParameter("hocphi", hocphi) :
                new ObjectParameter("hocphi", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemChuongTrinh", mactParameter, tenctParameter, thoigianParameter, hocphiParameter);
        }
    
        public virtual int sp_CapNhatGiaoVien(Nullable<short> magv, string ten, string sdt)
        {
            var magvParameter = magv.HasValue ?
                new ObjectParameter("magv", magv) :
                new ObjectParameter("magv", typeof(short));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatGiaoVien", magvParameter, tenParameter, sdtParameter);
        }
    
        public virtual ObjectResult<GIAOVIEN> sp_LietKeGiaoVien()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GIAOVIEN>("sp_LietKeGiaoVien");
        }
    
        public virtual int sp_ThemGiaoVien(string ten, string sdt)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemGiaoVien", tenParameter, sdtParameter);
        }
    
        public virtual int sp_XoaGiaoVien(Nullable<short> magv)
        {
            var magvParameter = magv.HasValue ?
                new ObjectParameter("magv", magv) :
                new ObjectParameter("magv", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaGiaoVien", magvParameter);
        }
    
        public virtual int sp_HuyLop(string malop)
        {
            var malopParameter = malop != null ?
                new ObjectParameter("malop", malop) :
                new ObjectParameter("malop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HuyLop", malopParameter);
        }
    
        public virtual int sp_ThemLop(string mact, Nullable<short> mach, Nullable<short> magv, Nullable<short> gioihan, Nullable<System.DateTime> ngaykhaigiang, Nullable<System.DateTime> ngayketthuc)
        {
            var mactParameter = mact != null ?
                new ObjectParameter("mact", mact) :
                new ObjectParameter("mact", typeof(string));
    
            var machParameter = mach.HasValue ?
                new ObjectParameter("mach", mach) :
                new ObjectParameter("mach", typeof(short));
    
            var magvParameter = magv.HasValue ?
                new ObjectParameter("magv", magv) :
                new ObjectParameter("magv", typeof(short));
    
            var gioihanParameter = gioihan.HasValue ?
                new ObjectParameter("gioihan", gioihan) :
                new ObjectParameter("gioihan", typeof(short));
    
            var ngaykhaigiangParameter = ngaykhaigiang.HasValue ?
                new ObjectParameter("ngaykhaigiang", ngaykhaigiang) :
                new ObjectParameter("ngaykhaigiang", typeof(System.DateTime));
    
            var ngayketthucParameter = ngayketthuc.HasValue ?
                new ObjectParameter("ngayketthuc", ngayketthuc) :
                new ObjectParameter("ngayketthuc", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemLop", mactParameter, machParameter, magvParameter, gioihanParameter, ngaykhaigiangParameter, ngayketthucParameter);
        }
    
        public virtual ObjectResult<LOP> sp_TimLop(string mact, Nullable<short> tinhtrang, Nullable<short> hienthi_moitrang, Nullable<short> trang)
        {
            var mactParameter = mact != null ?
                new ObjectParameter("mact", mact) :
                new ObjectParameter("mact", typeof(string));
    
            var tinhtrangParameter = tinhtrang.HasValue ?
                new ObjectParameter("tinhtrang", tinhtrang) :
                new ObjectParameter("tinhtrang", typeof(short));
    
            var hienthi_moitrangParameter = hienthi_moitrang.HasValue ?
                new ObjectParameter("hienthi_moitrang", hienthi_moitrang) :
                new ObjectParameter("hienthi_moitrang", typeof(short));
    
            var trangParameter = trang.HasValue ?
                new ObjectParameter("trang", trang) :
                new ObjectParameter("trang", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOP>("sp_TimLop", mactParameter, tinhtrangParameter, hienthi_moitrangParameter, trangParameter);
        }
    
        public virtual ObjectResult<LOP> sp_XemLop(string malop)
        {
            var malopParameter = malop != null ?
                new ObjectParameter("malop", malop) :
                new ObjectParameter("malop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOP>("sp_XemLop", malopParameter);
        }
    
        public virtual ObjectResult<HOCVIEN_LOP> sp_XemDanhSachLop(string malop)
        {
            var malopParameter = malop != null ?
                new ObjectParameter("malop", malop) :
                new ObjectParameter("malop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOCVIEN_LOP>("sp_XemDanhSachLop", malopParameter);
        }
    
        public virtual int sp_ThemHocVien(string ten, string sdt, string email)
        {
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var emailParameter = email != null ?
                new ObjectParameter("email", email) :
                new ObjectParameter("email", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThemHocVien", tenParameter, sdtParameter, emailParameter);
        }
    
        public virtual ObjectResult<HOCVIEN> sp_TimHocVien(string sdt, Nullable<short> hienthi_moitrang, Nullable<short> trang)
        {
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var hienthi_moitrangParameter = hienthi_moitrang.HasValue ?
                new ObjectParameter("hienthi_moitrang", hienthi_moitrang) :
                new ObjectParameter("hienthi_moitrang", typeof(short));
    
            var trangParameter = trang.HasValue ?
                new ObjectParameter("trang", trang) :
                new ObjectParameter("trang", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOCVIEN>("sp_TimHocVien", sdtParameter, hienthi_moitrangParameter, trangParameter);
        }
    
        public virtual ObjectResult<HOCVIEN> sp_XemHocVien(Nullable<int> mahv)
        {
            var mahvParameter = mahv.HasValue ?
                new ObjectParameter("mahv", mahv) :
                new ObjectParameter("mahv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOCVIEN>("sp_XemHocVien", mahvParameter);
        }
    
        public virtual int sp_DangKy(string malop, string sdt, string ten)
        {
            var malopParameter = malop != null ?
                new ObjectParameter("malop", malop) :
                new ObjectParameter("malop", typeof(string));
    
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var tenParameter = ten != null ?
                new ObjectParameter("ten", ten) :
                new ObjectParameter("ten", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_DangKy", malopParameter, sdtParameter, tenParameter);
        }
    
        public virtual int sp_HuyDangKy(Nullable<int> madk)
        {
            var madkParameter = madk.HasValue ?
                new ObjectParameter("madk", madk) :
                new ObjectParameter("madk", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HuyDangKy", madkParameter);
        }
    
        public virtual ObjectResult<DANGKY> sp_TimDangKy(string sdt, Nullable<short> loc, Nullable<short> hienthi_moitrang, Nullable<short> trang)
        {
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var locParameter = loc.HasValue ?
                new ObjectParameter("loc", loc) :
                new ObjectParameter("loc", typeof(short));
    
            var hienthi_moitrangParameter = hienthi_moitrang.HasValue ?
                new ObjectParameter("hienthi_moitrang", hienthi_moitrang) :
                new ObjectParameter("hienthi_moitrang", typeof(short));
    
            var trangParameter = trang.HasValue ?
                new ObjectParameter("trang", trang) :
                new ObjectParameter("trang", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DANGKY>("sp_TimDangKy", sdtParameter, locParameter, hienthi_moitrangParameter, trangParameter);
        }
    
        public virtual ObjectResult<GIAOVIEN> sp_XemGiaoVien(Nullable<short> magv)
        {
            var magvParameter = magv.HasValue ?
                new ObjectParameter("magv", magv) :
                new ObjectParameter("magv", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GIAOVIEN>("sp_XemGiaoVien", magvParameter);
        }
    
        public virtual ObjectResult<LICHSUDAY> sp_XemLichSuDay(Nullable<short> magv, Nullable<short> hienthi_moitrang, Nullable<short> trang)
        {
            var magvParameter = magv.HasValue ?
                new ObjectParameter("magv", magv) :
                new ObjectParameter("magv", typeof(short));
    
            var hienthi_moitrangParameter = hienthi_moitrang.HasValue ?
                new ObjectParameter("hienthi_moitrang", hienthi_moitrang) :
                new ObjectParameter("hienthi_moitrang", typeof(short));
    
            var trangParameter = trang.HasValue ?
                new ObjectParameter("trang", trang) :
                new ObjectParameter("trang", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LICHSUDAY>("sp_XemLichSuDay", magvParameter, hienthi_moitrangParameter, trangParameter);
        }
    
        public virtual ObjectResult<HOADON> sp_TimHoaDon(string sdt, Nullable<short> hienthi_moitrang, Nullable<short> trang)
        {
            var sdtParameter = sdt != null ?
                new ObjectParameter("sdt", sdt) :
                new ObjectParameter("sdt", typeof(string));
    
            var hienthi_moitrangParameter = hienthi_moitrang.HasValue ?
                new ObjectParameter("hienthi_moitrang", hienthi_moitrang) :
                new ObjectParameter("hienthi_moitrang", typeof(short));
    
            var trangParameter = trang.HasValue ?
                new ObjectParameter("trang", trang) :
                new ObjectParameter("trang", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOADON>("sp_TimHoaDon", sdtParameter, hienthi_moitrangParameter, trangParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_DongHocPhi(Nullable<int> mahv, string lops, string dks)
        {
            var mahvParameter = mahv.HasValue ?
                new ObjectParameter("mahv", mahv) :
                new ObjectParameter("mahv", typeof(int));
    
            var lopsParameter = lops != null ?
                new ObjectParameter("lops", lops) :
                new ObjectParameter("lops", typeof(string));
    
            var dksParameter = dks != null ?
                new ObjectParameter("dks", dks) :
                new ObjectParameter("dks", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_DongHocPhi", mahvParameter, lopsParameter, dksParameter);
        }
    
        public virtual ObjectResult<HOADON> sp_XemHoaDon(Nullable<int> mahd)
        {
            var mahdParameter = mahd.HasValue ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOADON>("sp_XemHoaDon", mahdParameter);
        }
    
        public virtual ObjectResult<LOP> sp_XemCacLopHoaDon(Nullable<int> mahd)
        {
            var mahdParameter = mahd.HasValue ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOP>("sp_XemCacLopHoaDon", mahdParameter);
        }
    
        public virtual int sp_ChuyenLop(Nullable<int> mahv, string malop_cu, string malop_moi)
        {
            var mahvParameter = mahv.HasValue ?
                new ObjectParameter("mahv", mahv) :
                new ObjectParameter("mahv", typeof(int));
    
            var malop_cuParameter = malop_cu != null ?
                new ObjectParameter("malop_cu", malop_cu) :
                new ObjectParameter("malop_cu", typeof(string));
    
            var malop_moiParameter = malop_moi != null ?
                new ObjectParameter("malop_moi", malop_moi) :
                new ObjectParameter("malop_moi", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChuyenLop", mahvParameter, malop_cuParameter, malop_moiParameter);
        }
    
        public virtual ObjectResult<LICHSUHOC> sp_XemLichSuHoc(Nullable<int> mahv)
        {
            var mahvParameter = mahv.HasValue ?
                new ObjectParameter("mahv", mahv) :
                new ObjectParameter("mahv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LICHSUHOC>("sp_XemLichSuHoc", mahvParameter);
        }
    
        public virtual ObjectResult<BAOLUU> sp_LietKeBaoLuu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<BAOLUU>("sp_LietKeBaoLuu");
        }
    
        public virtual int sp_BaoLuu(Nullable<int> mahv, string malop)
        {
            var mahvParameter = mahv.HasValue ?
                new ObjectParameter("mahv", mahv) :
                new ObjectParameter("mahv", typeof(int));
    
            var malopParameter = malop != null ?
                new ObjectParameter("malop", malop) :
                new ObjectParameter("malop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BaoLuu", mahvParameter, malopParameter);
        }
    
        public virtual int sp_HuyBaoLuu(Nullable<int> mahd, string malop)
        {
            var mahdParameter = mahd.HasValue ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(int));
    
            var malopParameter = malop != null ?
                new ObjectParameter("malop", malop) :
                new ObjectParameter("malop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_HuyBaoLuu", mahdParameter, malopParameter);
        }
    
        public virtual ObjectResult<HOCVIEN_LOP> sp_DanhSachChamDiem(string malop)
        {
            var malopParameter = malop != null ?
                new ObjectParameter("malop", malop) :
                new ObjectParameter("malop", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HOCVIEN_LOP>("sp_DanhSachChamDiem", malopParameter);
        }
    
        public virtual int sp_ChamDiem(Nullable<int> mahd, string malop, Nullable<double> diemchuyencan, Nullable<double> diemcuoiky)
        {
            var mahdParameter = mahd.HasValue ?
                new ObjectParameter("mahd", mahd) :
                new ObjectParameter("mahd", typeof(int));
    
            var malopParameter = malop != null ?
                new ObjectParameter("malop", malop) :
                new ObjectParameter("malop", typeof(string));
    
            var diemchuyencanParameter = diemchuyencan.HasValue ?
                new ObjectParameter("diemchuyencan", diemchuyencan) :
                new ObjectParameter("diemchuyencan", typeof(double));
    
            var diemcuoikyParameter = diemcuoiky.HasValue ?
                new ObjectParameter("diemcuoiky", diemcuoiky) :
                new ObjectParameter("diemcuoiky", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ChamDiem", mahdParameter, malopParameter, diemchuyencanParameter, diemcuoikyParameter);
        }
    
        public virtual ObjectResult<TAIKHOAN> sp_LietKeTaiKhoan()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TAIKHOAN>("sp_LietKeTaiKhoan");
        }
    
        public virtual int sp_TaoTaiKhoan(string username, string password, string loai)
        {
            var usernameParameter = username != null ?
                new ObjectParameter("username", username) :
                new ObjectParameter("username", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            var loaiParameter = loai != null ?
                new ObjectParameter("loai", loai) :
                new ObjectParameter("loai", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_TaoTaiKhoan", usernameParameter, passwordParameter, loaiParameter);
        }
    
        public virtual int sp_ThayDoiMatKhau(Nullable<short> matk, string password)
        {
            var matkParameter = matk.HasValue ?
                new ObjectParameter("matk", matk) :
                new ObjectParameter("matk", typeof(short));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ThayDoiMatKhau", matkParameter, passwordParameter);
        }
    
        public virtual int sp_XoaTaiKhoan(Nullable<short> matk)
        {
            var matkParameter = matk.HasValue ?
                new ObjectParameter("matk", matk) :
                new ObjectParameter("matk", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_XoaTaiKhoan", matkParameter);
        }
    
        public virtual int sp_BoTriGiaoVien(string malop, Nullable<short> magv)
        {
            var malopParameter = malop != null ?
                new ObjectParameter("malop", malop) :
                new ObjectParameter("malop", typeof(string));
    
            var magvParameter = magv.HasValue ?
                new ObjectParameter("magv", magv) :
                new ObjectParameter("magv", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BoTriGiaoVien", malopParameter, magvParameter);
        }
    
        public virtual int sp_CapNhatCaHoc(Nullable<short> mach, string giohoc, string ngayhoc)
        {
            var machParameter = mach.HasValue ?
                new ObjectParameter("mach", mach) :
                new ObjectParameter("mach", typeof(short));
    
            var giohocParameter = giohoc != null ?
                new ObjectParameter("giohoc", giohoc) :
                new ObjectParameter("giohoc", typeof(string));
    
            var ngayhocParameter = ngayhoc != null ?
                new ObjectParameter("ngayhoc", ngayhoc) :
                new ObjectParameter("ngayhoc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CapNhatCaHoc", machParameter, giohocParameter, ngayhocParameter);
        }
    
        public virtual ObjectResult<LOP> sp_XemLopDK(Nullable<int> madk)
        {
            var madkParameter = madk.HasValue ?
                new ObjectParameter("madk", madk) :
                new ObjectParameter("madk", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LOP>("sp_XemLopDK", madkParameter);
        }
    
        public virtual ObjectResult<DOANHTHU> sp_XemDoanhThu()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<DOANHTHU>("sp_XemDoanhThu");
        }
    }
}
